
export const Estate = [
    {
      id: 1,
      name: "follage",
      location: "Hyderabad",
      category: "flat",
      guests: 11,
      squareMeter: "1400",
      rating: 4.7,
      image: "/image.jpg",
      cost: "2.4cr",
    },
    {
      id: 2,
      name: "Villa ",
      location: "moinabad",
      category: "land",
      squareMeter: "450",
      rating: 4.4,
      image: "/IMAGE2.jpg",
      cost: "3CR",
    },
    {
      id: 3,
      name: "alpha",
      location: "moinabad",
      category: "land",
      squareMeter: "500",
      rating: 4.9,
      image: "/image3.jpg",
      cost: "2cr",
    },
    {
      id: 4,
      name: "koket",
      location: "hyderabad",
      category: "land",
      squareMeter: "750",
      rating: 5.0,
      image: "/image4.jpg",
      cost: "2cr",
    },
    {
      id: 5,
      name: "Boxane",
      location: "malakpet",
      category: "Mountains",
      squareMeter: "275",
      rating: 4.0,
      image: "/image5.jpg",
      cost: "2.6cr",
    },
    {
      id: 6,
      name: "gogreen",
      location: "amberpet",
      category: "land",
      squareMeter: "500",
      rating: 4.9,
      image: "/image6.jpg",
      cost: "3.2cr",
    },
    {
      id: 7,
      name: "lekke",
      location: "malakpet",
      category: "land",
      squareMeter: "1000",
      rating: 4.8,
      image: "/image7.jpg",
      cost: "280",
    },
    {
      id: 8,
      name: "jublie hills",
      location: "jublie hills",
      category: "land",
      squareMeter: "1500",
      rating: 5.0,
      image: "/image8.jpg",
      cost: "4cr",
    },
    {
      id: 9,
      name: "tulasi",
      location: "amberpet",
      category: "land",
      squareMeter: "240",
      rating: 3.8,
      image: "/image9.jpg",
      cost: "1.8cr",
    },
  ];
  
  